### ISSUE TITLE
GTK2 branch: applet.c:(.text+0x311): undefined reference to `trayicon_help'

### ISSUE THREAD

**Issue by Zenitur** [Newterm/florence#2]
Hello! I have a SUSE Linux Enterprise 11 with GNOME 2.28. I want to use Florence. I have already used it in Opensuse 11.4 (until it's livetime expired. Now I'm on SUSE Enterprise).

The error is in 0.5.2 and in the latest GIT of the GTK2 branch.

Repository: https://build.opensuse.org/package/show/home:linux4humans:sle11_software/florence
RPM SPEC file: https://build.opensuse.org/package/view_file/home:linux4humans:sle11_software/florence/florence.spec?expand=1
Full build log: [florence_gtk2_full_build_log.zip](https://github.com/Newterm/florence/files/597859/florence_gtk2_full_build_log.zip)

**Comment by tphaster** [comment]
Hi @Zenitur! This is probably not the repository, nor the website you're looking for with this bug report. In here we only have a fork of Florence with some small tweaks needed for our another project.

Please refer the original project's website at [https://sourceforge.net/projects/florence/](https://sourceforge.net/projects/florence/).

**Comment by Zenitur** [comment]
Thank you!
